# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kcdeUySkat_Dtm9OHmmvXgzXTMhrfPMy
"""

Import from sklearn.tree
 import DecisionTreeClassifier, export_text,
 plot_tree
 from sklearn.datasets
import make_classification
 import matplotlib.pyplot as plt
  # Sample simulated data X,
y = make_classification(n_samples=200
 n_features=4,
 random_state=42)
# Train decision tree
 clf = DecisionTreeClassifier(max_depth=4, random_state=42) clf.fit(X, y)
# Text Output print(export_text(clf, feature_names=["Creatinine", "AKI_Stage", "Age", "Preoperative_AKI"]))
  # Visual Plot plt.figure(figsize=(12, 8))
 plot_tree(clf,
 feature_names=["Creatinine", "AKI_Stage", "Age", "Preoperative_AKI"],
  class_names=["Survived", "Died/RRT"], filled=True) plt.title("Simulated AKI Decision Tree")
 plt.show()